# Defaults & plugin override
defaults:
  - _self_                             # Load this config file itself
  - override hydra/sweeper: HyperRS    # Replace Hydra’s default sweeper with Hypersweeper’s RandomSearch


# Global flags
seed: 42                             # Seed for reproducibility (env, policy, etc.)
n_trials: 50                         # Number of trials to be run 
num_episodes: 100                    # Number of episodes to run for each trial

# Hydra output & sweeper settings
hydra:
  run:
    dir: ./tmp/sarsa_rs              # Directory for single‐run outputs
  sweep:
    dir: ./tmp/sarsa_rs              # Directory where sweep results are stored
  sweeper:
    n_trials: ${n_trials}                      # Number of sampled configs (trials)
    sweeper_kwargs:
      max_parallelization: 0.8       # Fraction of trials to run in parallel (0.0–1.0)
      max_budget: 10000              # Optional budget cap (if your sweeper supports it)
    search_space: ${search_space}    # Reference to the `search_space` block below


# Environment instantiation
env:
  _target_: rl_exercises.environments.MarsRover
  transition_probabilities:                     # 5×2 matrix of probabilities in MarsRover
      - [1, 1]
      - [1, 1]
      - [1, 1]
      - [1, 1]
      - [1, 1]
  rewards: [1, -1, 0, 0, 10]         # Reward per cell index
  horizon: 200                       # Max steps per episode
  seed: ${seed}                      # Pass same seed into the env constructor


policy:
  _target_: rl_exercises.week_3.EpsilonGreedyPolicy
  epsilon: 0.1                       # Initial exploration rate
  seed: ${seed}                      # Seed for the policy’s internal RNG


agent:
  _target_: rl_exercises.week_3.SARSAAgent
  alpha: 0.5                         # Initial learning rate
  gamma: 0.99                        # Discount factor


search_space:
  seed: ${seed}                      # Seed for the sweeper’s random number generator
  hyperparameters:
    alpha:
      min: 0.1
      max: 1.0
      log: true
    epsilon:
      min: 0.01
      max: 0.5
      log: false
    gamma:
      min: 0.8
      max: 1.0
      log: false
